env:
  node: true
  es2021: true
extends: 
#  - 'airbnb-base'
  - 'eslint:recommended'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: 
  indent:
    - error
    - 4
  camelcase: 'off'
  strict: 'off'
  arrow-parens: 'off'
  no-plusplus: 'off'
  no-console: 'off'
  import/extensions: 'off'
